INSERT INTO Usr VALUES (1, 'George');
INSERT INTO Usr VALUES (2, 'Misha');

INSERT INTO Car VALUES ('Kia', 'Sportage', 1, 1);
INSERT INTO Car VALUES ('Nissan', 'Juke', 2, 2);
INSERT INTO ORD VALUES(1, 2, CURRENT_DATE);
INSERT INTO ORD VALUES(2, 1, CURRENT_DATE);

INSERT INTO SPR VALUES
('Wheel', 'Motors', 1, TO_DATE('2019', 'yyyy'), 800, 1);
INSERT INTO SPR VALUES
('Engine', 'Kawasaki', 2, TO_DATE('2015', 'yyyy'), 20000, 2);
