SELECT * FROM USR;

SELECT PRICE*2 as DOUBLE_PRICE FROM SPR ORDER BY price ASC;

SELECT USER_ID FROM ORD CONSTRAINT;

SELECT make || mode_car  FROM Car;

SELECT * FROM CAR ORDER BY CAR_ID ASC,USER_ID DESC;