
ALTER TABLE Car ADD CONSTRAINT pk_car PRIMARY KEY (car_id);
ALTER TABLE Usr ADD CONSTRAINT pk_usr PRIMARY KEY (user_id);
ALTER TABLE Ord ADD CONSTRAINT pk_ord PRIMARY KEY (order_id);
ALTER TABLE Spr ADD CONSTRAINT pk_spr PRIMARY KEY (spare_id);


ALTER TABLE Car ADD CONSTRAINT fk_car FOREIGN KEY (user_id) REFERENCES Usr(user_id);
ALTER TABLE Spr ADD CONSTRAINT fk_ord FOREIGN KEY (ord_id) REFERENCES Ord(order_id);
ALTER TABLE Ord ADD CONSTRAINT fk_spr FOREIGN KEY (user_id) REFERENCES Usr(user_id);

ALTER TABLE Spr ADD CONSTRAINT Spr_price_not_zero CHECK ( price > 0);

