
ALTER TABLE Car ADD CONSTRAINT PRIMARY KEY (car_id);
ALTER TABLE Ord ADD CONSTRAINT FOREIGN KEY (car_id) REFERENCES Usr(car_id)
ALTER TABLE Spr ADD CONSTRAINT Spr_price_not_zero
CHECK ( price > 0);

